Agoric/wallet-app

package.json, src/bridge-dapp.tsx, src/components/ConnectionSettingsDialog.tsx, src/components/SmartWalletConnection.tsx, src/service/Offers.ts, src/util/WalletBackendAdapter.ts, src/util/connections.ts, src/util/keyManagement.ts, yarn.lock
Some type annotations weren't yet converted to .ts syntax. This made them `any`.
Thankfully no errors were introduced in the time that these were untyped.
Incidentally, I checked whether we can enable `noImplicitAny` yet. 392 occurrences to address before that.
=> finish .ts adoption

src/components/AppBar.tsx, src/components/SmartWalletConnection.tsx, src/service/Offers.ts, src/store/Offers.ts, src/util/WalletBackendAdapter.ts, src/util/queryBankBalances.ts, src/util/querySwingsetParams.ts, yarn.lock
refs https://github.com/Agoric/wallet-app/issues/49
We still need to update dapp-inter to do the same, then I can test e2e with amounts in offer proposals rather than pursepetname+value
=> Query bank balances

src/service/Offers.ts, src/util/WalletBackendAdapter.ts
Tested locally with dapp-inter.
This lets dapps send amounts in offer proposals rather than pursePetnames+values now that purses are lazily instantiated from offers. Also fixes an issue where dapps couldn't use BigInts in offers since localstorage couldn't serialize raw BigInts. The serialized CapData amount can be written to localstorage just fine.
=> fix: make offers with amounts from dapps work

wallet/src/bridge-dapp.tsx, wallet/src/components/Offer.scss, wallet/src/components/Offer.tsx, wallet/src/components/Proposal.tsx, wallet/src/components/tests/Offer.test.jsx, wallet/src/contexts/Provider.tsx, wallet/src/service/Offers.ts, wallet/src/store/Offers.ts, wallet/src/util/WalletBackendAdapter.ts
fixes: https://github.com/Agoric/wallet-app/issues/61
- Adds exit button to currently-seated offers
- Adds refunded status for offers with 0 wants satisfied
Tested making liquidation bids from CLI and exiting them from UI
=> feat: allow exiting offers

wallet/src/components/Proposal.tsx
=> fix: display args as monospace

wallet/src/components/ProvisionDialog.tsx
If the provision pool is funded directly with IST rather than converting via the PSM, `totalMintedProvided` could be higher than `totalMintedConverted` and the subtraction could throw. It's probably better to read the IST balance directly rather than inferring this way, but the pool address isn't published anywhere currently, so for now just make sure it doesn't crash in this case.
=> fix: avoid error in provision pool calculation

wallet/src/bridge-dapp.tsx
https://github.com/Agoric/dapp-psm/issues/69 seems to be due to the Bridge connection logic.
1. open https://fix-cookies-error.wallet-app.pages.dev/wallet/ in one tab
2. open https://main.dapp-psm.pages.dev/?wallet=fix-cookies-error
3. disable Shields or Tracking Protection for PSM  site
4. click to Connect Keplr
5. in wallet click to Approve Dapp
5. in PSM verify "Successfully connected"
=> fix: third-party cookies error

wallet/src/rpc/src/batchQuery.ts, wallet/src/util/WalletBackendAdapter.ts
"Current Fees Accumulated" was always showing 0 because the query was failing silently. Fixed by using the correct vstorage path, and parsing the response correctly:
=> fix: read beansOwing correctly

wallet/src/util/chainInfo.ts, wallet/src/util/ibcTransfer.ts
Refs https://github.com/Agoric/dapp-inter/issues/199
=> fix: use network-config for ibc transfer rpc

wallet/src/components/ConnectionSettingsDialog.tsx, wallet/src/components/tests/ConnectionSettingsDialog.test.tsx, wallet/src/contexts/Provider.tsx, wallet/src/util/SuggestChain.ts, wallet/src/util/connections.ts, yarn.lock
fixes https://github.com/Agoric/wallet-app/issues/130
Adds auto-suggest inputs for rpc and api nodes. The suggestions are fetched from the currently selected network config. When the inputs are empty, it just defaults to a random node, so the inputs are not required.
=> feat: add node selectors to connection settings

package.json, wallet/package.json, yarn.lock
fixes https://github.com/Agoric/wallet-app/issues/140
=> chore: upgrade ses version

.github/workflows/e2e.yml, Dockerfile, package.json, test/e2e/docker-compose.yml, test/e2e/synpress.config.cjs, wallet/.dockerignore, yarn.lock
This PR adds a GitHub Action to execute end-to-end tests against PRs and merges to the main branch. 
The Github Action workflow involves running a `docker-compose` file that has these services defined:
`synpress`: Container responsible for running e2e tests.
`display`: Creates a display for the headed browser which is required by the `synpress` container. 
`ngrok`: Creates an external URL that can be used to VNC into the `display`.
=> ci setup for running e2e tests in wallet app

test/e2e/specs/test.spec.js
The PR adds a verification step post-wallet connection to confirm both ATOM and BLD tokens are visibly displayed on the screen.
=> test: check for existence of tokens after connecting with wallet

.github/workflows/e2e.yml, test/e2e/specs/test.spec.js
This PR adds a scheduled run the `e2e.yml` github action to run it once daily.
It also updates the tests to remove an extra call to `setupWallet`. this call is already triggered by `synpress` by default when the `SKIP_EXTENSION_SETUP` env variable is not provided. so it isn't needed here
=> ci: added daily scheduled run to e2e test workflow

test/e2e/constants.js, test/e2e/specs/test.spec.js
The PR adds a test case that involves:
- Creating a brand new wallet. 
- Obtaining funds from the faucet. 
- Provisioning the wallet.
=> test: add test for provisioning a brand new wallet

test/e2e/specs/test.spec.js, test/e2e/synpress.config.cjs, test/e2e/test.utils.js
The PR does the following:
- Eliminates fragile selectors used in e2e test cases. 
- Increase timeouts for some tests to ensure stability with emerynet.
=> refactor: remove fragile selectors

.github/workflows/e2e.yml
Refs: https://github.com/Agoric/dapp-econ-gov/issues/111
Fixes some flakes in e2e testing.
- Firstly used docker compose instead of docker-compose (which is not being recognized by github actions)
- Secondly removed some unnecessary steps to give some space to the github runner, otherwise the job was failing due to space limit being reached
=> ci: change docker-compose to docker compose

Dockerfile
This PR updates the `agoric-sdk` image used in CI for end-to-end tests to the latest version.
=> ci: use latest agoric-sdk image

.github/workflows/e2e.yml, test/e2e/docker-compose.yml
The PR introduces a new profile called `daily-tests` in the Docker Compose file. Profiles are used to configure containers for scheduled runs and when testing against a PR.
=> ci: adding profiles to differeniate between scheduled and PR test runs

test/e2e/specs/test.spec.js, test/e2e/test.utils.js
After updating the `ses` version in #187, the `a3p` chain is working fine with the wallet app. This PR updates the e2e tests to use the `localhost` URL when `AGORIC_NET` is `local`. 
closes #184
=> URL changes in e2e tests to make it work locally

.github/workflows/e2e.yml, Dockerfile, test/e2e/docker-compose.yml
This PR enables specifying a tag value for the `agoric-sdk` image in CI, allowing end-to-end tests to run with the provided tag.
=> ci: input agoric-sdk image tag

test/e2e/specs/test.spec.js
Adding a wait of 5 seconds before trying to look for the Keplr popup. 
Seems to be passing CI at the moment. Will see how it performs in the scheduled runs in the coming days.
=> test: add wait before checking keplr popup

test/e2e/specs/test.spec.js, test/e2e/support.js, test/e2e/test.utils.js
The PR does the following:
- Addresses flaky tests related to provisioning the wallet via splitting the relevant test case into two test cases i.e. creating a new wallet and then performing the provision part. Making it easier to find the faulty section of the test case. 
- Ensures the test case waits for the appropriate amount of time while the wallet is being provided. 
- Creates a custom command that gets the IST balance for the given wallet address via an API call. This command is programmed to work with all of our testnets and A3P. 
- Making use of the custom command to verify IST balance before and after placing the bid. Verification of IST balance has been failing lately perhaps because of a UI inconsistency. By verifying the IST balance via an API call, we no longer depend on UI …
=> fix flaky e2e tests
